import type { Metadata } from "next";
import { Inter } from "next/font/google"
import { AuthProvider } from "@/contexts/AuthContext";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes"
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <AuthProvider>
          <Theme accentColor="blue" grayColor="gray" hasBackground={true}>
            {children}
          </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
